Retag previous newest image to latest after delete

diff --git a/.github/workflows/nightly-deploy.yml b/.github/workflows/nightly-deploy.yml
--- a/.github/workflows/nightly-deploy.yml
+++ b/.github/workflows/nightly-deploy.yml
@@ -100,78 +100,19 @@ jobs:
             newgrp docker
             docker --version
             docker-compose version
-               
+
             export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
             export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
             export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
             export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
             export AWS_REGION=${{ env.AWS_REGION }}
 
-            aws ecr get-login-password --region \$AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com            
+            aws ecr get-login-password --region \$AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com
             docker-compose -f docker-compose-test.yml up -d
             sleep 10
 
             curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5173/ | grep -q 200 || exit 1
           EOF
-
-
-#      - name: Provision Application on EC2 and Run Smoke Tests
-#        run: |
-#          PUBLIC_DNS=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} \
-#            --query 'Reservations[0].Instances[0].PublicDnsName' \
-#            --output text)
-#          echo "PUBLIC_DNS=$PUBLIC_DNS" >> $GITHUB_ENV
-#          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@$PUBLIC_DNS << EOF
-#            sudo yum install git -y
-#            sudo yum install -y docker
-#            sudo service docker start
-#            sudo chkconfig docker on
-#            sudo usermod -aG docker ec2-user
-#            sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
-#            sudo chmod +x /usr/local/bin/docker-compose
-#            newgrp docker
-#            git --version
-#            docker --version
-#            docker-compose version
-#            sudo dnf install -y mariadb105
-#            mysql --version
-#
-#            git clone $SOURCE_REPO app
-#            cd app
-#
-#            docker-compose up -d
-#            sleep 10
-#
-#            curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5173/ | grep -q 200 || exit 1
-#          EOF
-#
-#      - name: Push Docker Images to ECR
-#        run: |
-#          ssh -i ec2-key.pem ec2-user@${{ env.PUBLIC_DNS }} << EOF
-#            export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
-#            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
-#            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
-#            export AWS_REGION=${{ env.AWS_REGION }}
-#            IMAGE_TAG=${{ env.IMAGE_TAG }}
-#
-#            FRONTEND_IMAGE_ID=\$(docker images --filter=reference="app-frontend" --format "{{.ID}}")
-#            BACKEND_IMAGE_ID=\$(docker images --filter=reference="app-backend" --format "{{.ID}}")
-#            echo "Found Docker Image ID (frontend): \$FRONTEND_IMAGE_ID"
-#            echo "Found Docker Image ID (backend): \$BACKEND_IMAGE_ID"
-#
-#            aws ecr get-login-password --region \$AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com
-#
-#            TIMESTAMP=$(date "+%Y%m%d.%H%M%S")
-#
-#            docker tag \$FRONTEND_IMAGE_ID ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY_FRONTEND }}:\$TIMESTAMP
-#            docker tag \$FRONTEND_IMAGE_ID ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY_FRONTEND }}:\$IMAGE_TAG
-#            docker push --all-tags ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY_FRONTEND }}
-#
-#            docker tag \$BACKEND_IMAGE_ID ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY_BACKEND }}:\$TIMESTAMP
-#            docker tag \$BACKEND_IMAGE_ID ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY_BACKEND }}:\$IMAGE_TAG
-#            docker push --all-tags ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.\$AWS_REGION.amazonaws.com/${{ secrets.ECR_REPOSITORY_BACKEND }}
-#          EOF
 
       - name: Deploy to QA EC2
         if: success()
@@ -194,14 +135,42 @@ jobs:
             docker-compose -f docker-compose-qa.yml up -d
             docker image prune -f
           EOF
-
       - name: Delete Images in ECR if Test Fails
         if: failure()
         run: |
           echo "Smoke test failed. Cleaning up Docker images in ECR..."
+          
+          PRE_FRONTEND_IMAGE_TAG=$(aws ecr list-images --repository-name book-app/frontend \
+            --query 'imageIds[?imageTag!=`latest`].[imageTag]' --output text | sort -r | sed -n '2p')
+          PRE_BACKEND_IMAGE_TAG=$(aws ecr list-images --repository-name book-app/backend \
+            --query 'imageIds[?imageTag!=`latest`].[imageTag]' --output text | sort -r | sed -n '2p')
+          
           aws ecr batch-delete-image --repository-name book-app/frontend --image-ids imageTag=${{ env.TIMESTAMP }}
+          aws ecr batch-delete-image --repository-name book-app/frontend --image-ids imageTag=${{ env.IMAGE_TAG }}
           aws ecr batch-delete-image --repository-name book-app/backend --image-ids imageTag=${{ env.TIMESTAMP }}
-        
+          aws ecr batch-delete-image --repository-name book-app/backend --image-ids imageTag=${{ env.IMAGE_TAG }}
+
+          if [ -z "$PRE_FRONTEND_IMAGE_TAG" ]; then
+            echo "❌ No previous images found. Cannot restore 'latest'."
+            exit 1
+          fi
+          
+          if [ -z "$PRE_BACKEND_IMAGE_TAG" ]; then
+            echo "❌ No previous images found. Cannot restore 'latest'."
+            exit 1
+          fi
+
+          echo "🔄 Previous valid frontend image found: $PRE_FRONTEND_IMAGE_TAG"
+          echo "🔄 Previous valid backend image found: $PRE_BACKEND_IMAGE_TAG"
+          
+          # Save the image manifest to a file for security
+          FRONTEND_MANIFEST=$(aws ecr batch-get-image --repository-name book-app/frontend --image-ids imageTag="$PRE_FRONTEND_IMAGE_TAG" --output text --query 'images[].imageManifest')
+          BACKEND_MANIFEST=$(aws ecr batch-get-image --repository-name book-app/backend --image-ids imageTag="$PRE_BACKEND_IMAGE_TAG" --output text --query 'images[].imageManifest')
+
+          # Retag
+          aws ecr put-image --repository-name book-app/frontend --image-tag ${{ env.IMAGE_TAG }} --image-manifest "$FRONTEND_MANIFEST"
+          aws ecr put-image --repository-name book-app/backend --image-tag ${{ env.IMAGE_TAG }} --image-manifest "$BACKEND_MANIFEST"
+          
 
       - name: Terminate Temporary EC2 Instance
         run: |
